name: D

on: push

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1

    - name: 'Setup'
      run: |
        git submodule update --init --recursive
        sudo apt-get install xorg-dev

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2 -B release
  
  build-redbuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'redbuild'
      run: |
        ./redbuild.sh

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: 'Setup'
      run: |
        git submodule update --init --recursive

        ls /System/Library/Frameworks/
        brew install glew
        brew install glfw

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2 -B release

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1

    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Setup'
      run: |
        git submodule update --init --recursive

        curl -L https://github.com/ldc-developers/ldc/releases/download/v1.29.0/ldc2-1.29.0-windows-x64.7z --output ldc2-1.29.0-windows-x64.7z
        7z x ldc2-1.29.0-windows-x64.7z
        curl -L https://github.com/redthing1/dray/releases/download/v4.0.0-r4/draylibs_dev_win64_msvc16.7z --output draylibs_dev_win64_msvc16.7z
        7z x draylibs_dev_win64_msvc16.7z
        curl -L https://github.com/redthing1/dray/releases/download/v4.0.0-r3/winlibs_extra.7z --output winlibs_extra.7z
        7z x winlibs_extra.7z
        curl -L https://github.com/glfw/glfw/releases/download/3.3.7/glfw-3.3.7.bin.WIN64.zip --output glfw-3.3.7.bin.WIN64.zip
        unzip glfw-3.3.7.bin.WIN64.zip

        move glfw-3.3.7.bin.WIN64/lib-vc2022/glfw3_mt.lib ./glfw3_mt.lib

        cd ext

        git clone https://github.com/redthing1/dray/

        cd dray
        move ../../draylibs_dev_win64_msvc16/raylib.lib ./raylib.lib
        move ../../WinMM.lib ./WinMM.lib

        set WINLIB_BASE="../../ldc2-1.28.1-windows-x64/lib/"
        set WINLIB_MINGW="../../ldc2-1.28.1-windows-x64/lib/mingw"
        echo $WINLIB_BASE
        dub build --compiler ldc2 -B release

        cd ../..

        move ext/dray/WinMM.lib ./WinMM.lib

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests

        dub add-override dray "4.0.0-r5" ./ext/dray
        move ext/dray/raylib.lib ./raylib.lib
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2 -B release
