name: D

on: push

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.30.0

    - name: 'Setup'
      run: |
        git submodule update --init --recursive
        sudo apt-get install xorg-dev

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2
  
  build-redbuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'redbuild'
      run: |
        ./redbuild.sh

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.30.0
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: 'Setup'
      run: |
        git submodule update --init --recursive

        ls /System/Library/Frameworks/
        brew install glew
        brew install glfw
        brew install coreutils

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests
        export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2

  build-windows:
    runs-on: windows-latest
    env:
      DRAY_VERSION: 4.2.0-r2

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ldc-1.30.0

    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Setup'
      run: |
        start setup_windows.bat

    - name: 'Build BeanDS'
      run: |
        # Build the project, with its main file included, without unittests

        dub add-override dray $env:DRAY_VERSION ./ext/dray
        move ext/dray/raylib.lib ./raylib.lib
        dub build --compiler ldc2 -B release
    
    - name: 'Run Tests'
      run: |
        dub test --compiler ldc2
        ./beands foo
